#!/usr/bin/env bash
set -euo pipefail

# eventstracker/dev-up.sh
# Starts local event-service-db from the central jubilant-memory/config stack.
# Called directly or by consolidated-postgres/scripts/local/multi-dev-up.sh
#
# Usage: ./dev-up.sh [--reset] [--cloud] [--help]
#   --reset   Drop and recreate event-service-db container
#   --cloud   Write cloud DB credentials to .env (reads ../.env.cloud)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

DB_PORT=6433
DB_NAME="event-service"
CONTAINER_NAME="event-service-db"
CLOUD_ENV_FILE="$SCRIPT_DIR/../consolidated-postgres/.env.cloud"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
print_status() { echo -e "${GREEN}✓${NC} $1"; }
print_error()  { echo -e "${RED}✗${NC} $1"; }
print_info()   { echo -e "${YELLOW}ℹ${NC} $1"; }

RESET_DB=false; CLOUD_MODE=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --reset) RESET_DB=true; shift ;;
    --cloud) CLOUD_MODE=true; shift ;;
    --help)  grep "^#" "$0" | head -12 | sed 's/^# \?//'; exit 0 ;;
    *)       print_error "Unknown option: $1"; exit 1 ;;
  esac
done

if ! docker ps > /dev/null 2>&1; then
  print_error "Docker is not running"; exit 1
fi

# Save existing app-level secrets from .env before any writes
_saved_event_user=""
_saved_event_pass=""
_saved_config_user=""
_saved_config_pass=""
_saved_rabbit_user=""
_saved_rabbit_pass=""
if [ -f ".env" ]; then
  _saved_event_user=$(grep -E "^EVENT_DOMAIN_USER=" .env | tail -1 | cut -d= -f2- || true)
  _saved_event_pass=$(grep -E "^EVENT_DOMAIN_USER_PASSWORD=" .env | tail -1 | cut -d= -f2- || true)
  _saved_config_user=$(grep -E "^SPRING_CLOUD_CONFIG_USERNAME=" .env | tail -1 | cut -d= -f2- || true)
  _saved_config_pass=$(grep -E "^SPRING_CLOUD_CONFIG_PASSWORD=" .env | tail -1 | cut -d= -f2- || true)
  _saved_rabbit_user=$(grep -E "^RABBITMQ_USERNAME=" .env | tail -1 | cut -d= -f2- || true)
  _saved_rabbit_pass=$(grep -E "^RABBITMQ_PASSWORD=" .env | tail -1 | cut -d= -f2- || true)
fi

# ─── Cloud mode ──────────────────────────────────────────────────────────────
if [ "$CLOUD_MODE" = true ]; then
  print_info "Configuring eventstracker for cloud database..."

  [ -f "$CLOUD_ENV_FILE" ] || {
    print_error "Run consolidated-postgres/cloud-start.sh first — $CLOUD_ENV_FILE not found"
    exit 1
  }

  _fetch() { grep -E "^$1=" "$CLOUD_ENV_FILE" | tail -1 | cut -d= -f2-; }
  _db_url=$(  _fetch "EVENTS_TRACKER_DB_URL")
  _db_user=$( _fetch "EVENTS_TRACKER_DB_USER")
  _db_pass=$( _fetch "EVENTS_TRACKER_DB_PASSWORD")

  [ -n "$_db_url"  ] || { print_error "EVENTS_TRACKER_DB_URL missing in $CLOUD_ENV_FILE";  exit 1; }
  [ -n "$_db_user" ] || { print_error "EVENTS_TRACKER_DB_USER missing in $CLOUD_ENV_FILE"; exit 1; }
  [ -n "$_db_pass" ] || { print_error "EVENTS_TRACKER_DB_PASSWORD missing in $CLOUD_ENV_FILE"; exit 1; }

  _rabbit_user="${RABBITMQ_USERNAME:-$_saved_rabbit_user}"
  _rabbit_pass="${RABBITMQ_PASSWORD:-$_saved_rabbit_pass}"
  [ -n "$_rabbit_user" ] || { print_error "RABBITMQ_USERNAME not set (export it or set it in eventstracker/.env)"; exit 1; }
  [ -n "$_rabbit_pass" ] || { print_error "RABBITMQ_PASSWORD not set (export it or set it in eventstracker/.env)"; exit 1; }

  cat > .env << EOF
# eventstracker - cloud DB - generated by dev-up.sh --cloud - DO NOT COMMIT
EVENTS_TRACKER_DB_URL=${_db_url}
EVENTS_TRACKER_DB_USER=${_db_user}
EVENTS_TRACKER_DB_PASSWORD=${_db_pass}
RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USERNAME=${_rabbit_user}
RABBITMQ_PASSWORD=${_rabbit_pass}
EVENT_DOMAIN_USER=${_saved_event_user}
EVENT_DOMAIN_USER_PASSWORD=${_saved_event_pass}
SPRING_CLOUD_CONFIG_USERNAME=${_saved_config_user}
SPRING_CLOUD_CONFIG_PASSWORD=${_saved_config_pass}
EOF
  chmod 600 .env
  print_status "Cloud .env written"
  print_info "Run: SPRING_PROFILES_ACTIVE=prod mvn spring-boot:run"
  exit 0
fi

# ─── Local mode: start via jubilant-memory central stack ─────────────────────
INFRA_DIR=""
for _candidate in \
    "$SCRIPT_DIR/../jubilant-memory/config" \
    "$HOME/IdeaProjects/jubilant-memory/config"; do
  if [ -f "$_candidate/docker-compose.yml" ]; then
    INFRA_DIR="$(cd "$_candidate" && pwd)"
    break
  fi
done

[ -n "$INFRA_DIR" ] || {
  print_error "Cannot find jubilant-memory/config — clone jubilant-memory as a sibling of eventstracker"
  exit 1
}
print_info "Infrastructure: $INFRA_DIR"

# Require infra .env to be machine-local and explicit (no insecure defaults)
_INFRA_ENV="$INFRA_DIR/.env"
if [ ! -f "$_INFRA_ENV" ]; then
  print_error "Missing $_INFRA_ENV"
  print_info "Create it from template: cp $INFRA_DIR/.env.example $_INFRA_ENV"
  print_info "Then set EVENTS_TRACKER_DB_USER, EVENTS_TRACKER_DB_PASSWORD, RABBITMQ_USERNAME, RABBITMQ_PASSWORD"
  exit 1
fi

# shellcheck source=/dev/null
set -a; source "$_INFRA_ENV"; set +a

_required_vars=(EVENTS_TRACKER_DB_USER EVENTS_TRACKER_DB_PASSWORD RABBITMQ_USERNAME RABBITMQ_PASSWORD)
for _v in "${_required_vars[@]}"; do
  if [ -z "${!_v:-}" ]; then
    print_error "$_v not set in $_INFRA_ENV"
    exit 1
  fi
done

if [ "$RESET_DB" = true ]; then
  print_info "Resetting event-service-db..."
  docker stop "$CONTAINER_NAME" 2>/dev/null || true
  docker rm   "$CONTAINER_NAME" 2>/dev/null || true
fi

if docker ps --filter "name=^${CONTAINER_NAME}$" --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
  print_status "event-service-db already running on :$DB_PORT"
else
  print_info "Starting event-service-db via jubilant-memory stack..."
  docker compose -f "$INFRA_DIR/docker-compose.yml" up -d postgres
fi

# Wait for readiness
print_info "Waiting for PostgreSQL on :$DB_PORT..."
_ready=false
for _i in $(seq 1 30); do
  if docker exec "$CONTAINER_NAME" pg_isready -U "$EVENTS_TRACKER_DB_USER" >/dev/null 2>&1; then
    _ready=true; break
  fi
  sleep 1
done
[ "$_ready" = true ] || { print_error "PostgreSQL did not become ready within 30s"; exit 1; }
print_status "PostgreSQL ready on :$DB_PORT"

# Keep DB role in sync with configured credentials (handles existing containers)
if [ -z "$EVENTS_TRACKER_DB_USER" ]; then
  print_error "EVENTS_TRACKER_DB_USER is empty — cannot sync role"; exit 1
fi

# Detect the actual superuser inside the running container.
# POSTGRES_USER is set at container init time and may differ from the current .env value.
_superuser=$(docker exec "$CONTAINER_NAME" printenv POSTGRES_USER 2>/dev/null || echo "postgres")
print_info "Container superuser: '${_superuser}', desired DB user: '${EVENTS_TRACKER_DB_USER}'"

# Idempotent: create role if missing, always sync password and grants
docker exec "$CONTAINER_NAME" psql -U "$_superuser" -d postgres -c \
  "DO \$\$
   BEGIN
     CREATE ROLE \"${EVENTS_TRACKER_DB_USER}\" LOGIN PASSWORD '${EVENTS_TRACKER_DB_PASSWORD}';
   EXCEPTION WHEN duplicate_object THEN NULL;
   END \$\$;" >/dev/null
docker exec "$CONTAINER_NAME" psql -U "$_superuser" -d postgres -c \
  "ALTER ROLE \"${EVENTS_TRACKER_DB_USER}\" WITH LOGIN PASSWORD '${EVENTS_TRACKER_DB_PASSWORD}';" >/dev/null
print_status "DB role synced: ${EVENTS_TRACKER_DB_USER}"

docker exec "$CONTAINER_NAME" psql -U "$_superuser" -d postgres -c \
  "GRANT ALL PRIVILEGES ON DATABASE \"${DB_NAME}\" TO \"${EVENTS_TRACKER_DB_USER}\";" >/dev/null || true

# Write .env with local Docker values, preserving app-level secrets
cat > .env << EOF
# eventstracker - local Docker - generated by dev-up.sh - DO NOT COMMIT
EVENTS_TRACKER_DB_URL=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
EVENTS_TRACKER_DB_USER=${EVENTS_TRACKER_DB_USER}
EVENTS_TRACKER_DB_PASSWORD=${EVENTS_TRACKER_DB_PASSWORD}
RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
EVENT_DOMAIN_USER=${_saved_event_user}
EVENT_DOMAIN_USER_PASSWORD=${_saved_event_pass}
SPRING_CLOUD_CONFIG_USERNAME=${_saved_config_user}
SPRING_CLOUD_CONFIG_PASSWORD=${_saved_config_pass}
EOF
chmod 600 .env

print_status ".env written (DB + RabbitMQ loaded from jubilant-memory/config/.env)"
for _var in EVENT_DOMAIN_USER EVENT_DOMAIN_USER_PASSWORD SPRING_CLOUD_CONFIG_USERNAME SPRING_CLOUD_CONFIG_PASSWORD; do
  _val=$(grep -E "^${_var}=" .env | cut -d= -f2- || true)
  [ -n "$_val" ] || print_info "  ⚠ ${_var} is empty — edit .env before starting the app"
done
print_status "eventstracker local environment ready"
print_info "Run: mvn spring-boot:run -Dspring-boot.run.profiles=local"

