#!/usr/bin/env bash
set -euo pipefail

#################################################################
# EventTracker Development Environment Startup
#
# Usage: ./dev-up.sh [options]
#
# Options:
#   --reset     Drop and recreate database (clean slate)
#   --help      Show this help message
#
# What it does:
#   1. Starts PostgreSQL in Docker
#   2. Waits for database to be ready
#   3. Creates/updates .env file with connection details
#   4. Runs Flyway migrations automatically (when app starts)
#
# Next steps:
#   mvn spring-boot:run
#   or use your IDE's "Run" button
#################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Configuration
CONTAINER_NAME="eventstracker-postgres"
DB_NAME="eventstracker_db"
DB_USER="postgres"
DB_PASSWORD="postgres"
DB_PORT=5432
APP_PORT=9081
CLOUD_ENV_FILE="$SCRIPT_DIR/../consolidated-postgres/.env.cloud"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
RESET_DB=false
CLOUD_MODE=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --reset)
      RESET_DB=true
      shift
      ;;
    --cloud)
      CLOUD_MODE=true
      shift
      ;;
    --help)
      head -n 20 "$0" | tail -n +2
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

print_status() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_info() {
  echo -e "${YELLOW}ℹ${NC} $1"
}

fetch_cloud_value() {
  local key="$1"
  if [ ! -f "$CLOUD_ENV_FILE" ]; then
    print_error "Cloud configuration not found at $CLOUD_ENV_FILE"
    exit 1
  fi
  local value
  value=$(grep -E "^${key}=" "$CLOUD_ENV_FILE" | tail -n 1 | cut -d'=' -f2-)
  if [ -z "$value" ]; then
    print_error "Missing value for $key in $CLOUD_ENV_FILE"
    exit 1
  fi
  echo "$value"
}

write_cloud_env() {
  local jdbc_url="$1"
  local username="$2"
  local password="$3"
  local host="$4"
  local port="$5"
  local db_name="$6"
  local sslmode="$7"

  cat > .env << EOF
# EventTracker Cloud Database Configuration
# Generated by dev-up.sh --cloud - do not commit to git

# Database Connection
DB_HOST=$host
DB_PORT=$port
DB_NAME=$db_name
DB_USERNAME=$username
DB_PASSWORD=$password
DB_SSLMODE=$sslmode

# JDBC URLs
JDBC_DATABASE_URL=$jdbc_url
eventstracker_JDBC_DATABASE_URL=$jdbc_url
eventstracker_JDBC_DATABASE_USERNAME=$username
eventstracker_JDBC_DATABASE_PASSWORD=$password

# RabbitMQ (cloud mode assumes external configuration)
RABBITMQ_HOST=${RABBITMQ_HOST:-localhost}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}

# Application Server
SERVER_PORT=$APP_PORT
EOF
  print_status "Cloud .env file created"
}

generate_cloud_configuration() {
  if [ "$RESET_DB" = true ]; then
    print_info "--reset is ignored in cloud mode"
  fi

  local jdbc_url username password sslmode
  jdbc_url=$(fetch_cloud_value "EVENTSTRACKER_DATASOURCE_URL")
  username=$(fetch_cloud_value "EVENTSTRACKER_DATASOURCE_USERNAME")
  password=$(fetch_cloud_value "EVENTSTRACKER_DATASOURCE_PASSWORD")
  sslmode="require"

  local url_body host_port db_and_query host port db_name
  url_body=${jdbc_url#jdbc:postgresql://}
  host_port=${url_body%%/*}
  db_and_query=${url_body#*/}
  host=${host_port%%:*}
  port=${host_port##*:}
  db_name=${db_and_query%%\?*}

  if [ -z "$host" ] || [ -z "$port" ] || [ -z "$db_name" ]; then
    print_error "Failed to parse JDBC URL from cloud configuration"
    exit 1
  fi

  print_info "Using DigitalOcean database at $host:$port/$db_name"
  write_cloud_env "$jdbc_url" "$username" "$password" "$host" "$port" "$db_name" "$sslmode"

  print_status "EventTracker configured for cloud database"
  cat <<EOT

════════════════════════════════════════════════════════════════
ℹ EventTracker cloud configuration ready
════════════════════════════════════════════════════════════════

Database Details:
  Host:     $host
  Port:     $port (SSL mode: $sslmode)
  Database: $db_name
  User:     $username

Next Steps:
  1. Ensure cloud infrastructure is started (./cloud-start.sh)
  2. Run the application:
     mvn spring-boot:run

If the cloud database is not reachable, rerun without --cloud to use local Docker.

════════════════════════════════════════════════════════════════

EOT
}

if [ "$CLOUD_MODE" = true ]; then
  generate_cloud_configuration
  exit 0
fi

# Check if Docker is running
if ! docker ps > /dev/null 2>&1; then
  print_error "Docker is not running. Please start Docker and try again."
  exit 1
fi

print_info "Starting EventTracker development environment..."

# Handle reset flag
if [ "$RESET_DB" = true ]; then
  print_info "Resetting database (--reset flag set)..."
  if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1; then
    docker compose down -v
    print_status "Database reset"
  fi
fi

# Start Docker container
print_info "Starting PostgreSQL container..."
if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1 && docker ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"; then
  print_status "PostgreSQL already running on port $DB_PORT"
else
  docker compose up -d
  print_status "PostgreSQL started"
fi

# Wait for PostgreSQL to be ready
print_info "Waiting for PostgreSQL to be ready..."
max_attempts=30
attempt=0

while [ $attempt -lt $max_attempts ]; do
  if docker exec "$CONTAINER_NAME" pg_isready -U "$DB_USER" > /dev/null 2>&1; then
    print_status "PostgreSQL is ready"
    break
  fi
  attempt=$((attempt + 1))
  sleep 1
done

if [ $attempt -eq $max_attempts ]; then
  print_error "PostgreSQL failed to start within ${max_attempts}s"
  print_info "Check logs with: docker logs $CONTAINER_NAME"
  exit 1
fi

# Create .env file
print_info "Creating .env file..."
cat > .env << EOF
# EventTracker Database Configuration
# Generated by dev-up.sh - do not commit to git

# Database Connection
DB_HOST=localhost
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USERNAME=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Full JDBC URL (used by Spring Boot)
JDBC_DATABASE_URL=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME

# Spring Boot Specific
spring.datasource.url=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME
spring.datasource.username=$DB_USER
spring.datasource.password=$DB_PASSWORD

# Alternative: Environment variable names expected by application.yml
eventstracker_JDBC_DATABASE_URL=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME
eventstracker_JDBC_DATABASE_USERNAME=$DB_USER
eventstracker_JDBC_DATABASE_PASSWORD=$DB_PASSWORD

# RabbitMQ (local defaults, adjust if needed)
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest

# Application Server
SERVER_PORT=$APP_PORT
EOF

print_status ".env file created"

# Verify database exists
print_info "Verifying database..."
if docker exec -i "$CONTAINER_NAME" psql -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;" > /dev/null 2>&1; then
  print_status "Database verified"
else
  print_error "Failed to verify database"
  exit 1
fi

# Print next steps
echo ""
echo "════════════════════════════════════════════════════════════════"
echo -e "${GREEN}✓ EventTracker is ready!${NC}"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Database Details:"
echo "  Host:     localhost"
echo "  Port:     $DB_PORT"
echo "  Database: $DB_NAME"
echo "  User:     $DB_USER"
echo "  Password: $DB_PASSWORD"
echo ""
echo "Next Steps:"
echo "  1. Run the application:"
echo "     mvn spring-boot:run"
echo ""
echo "  2. Flyway migrations will run automatically on startup"
echo ""
echo "  3. View pgAdmin (optional):"
echo "     docker compose --profile pgadmin up -d"
echo "     Then: http://localhost:5050 (admin/admin)"
echo ""
echo "Useful Commands:"
echo "  Stop database:    docker compose down"
echo "  View logs:        docker logs $CONTAINER_NAME"
echo "  Connect via psql: psql -h localhost -U $DB_USER -d $DB_NAME"
echo "  Reset database:   ./dev-up.sh --reset"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
