#!/usr/bin/env bash
set -euo pipefail

#################################################################
# EventTracker Development Environment Startup
#
# Usage: ./dev-up.sh [options]
#
# Options:
#   --reset     Drop and recreate database (clean slate)
#   --help      Show this help message
#
# What it does:
#   1. Starts PostgreSQL in Docker
#   2. Waits for database to be ready
#   3. Creates/updates .env file with connection details
#   4. Runs Flyway migrations automatically (when app starts)
#
# Next steps:
#   mvn spring-boot:run
#   or use your IDE's "Run" button
#################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Configuration
CONTAINER_NAME="eventstracker-postgres"
DB_NAME="eventstracker_db"
DB_USER="postgres"
DB_PASSWORD="postgres"
DB_PORT=5432
APP_PORT=9081

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
RESET_DB=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --reset)
      RESET_DB=true
      shift
      ;;
    --help)
      head -n 20 "$0" | tail -n +2
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

print_status() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_info() {
  echo -e "${YELLOW}ℹ${NC} $1"
}

# Check if Docker is running
if ! docker ps > /dev/null 2>&1; then
  print_error "Docker is not running. Please start Docker and try again."
  exit 1
fi

print_info "Starting EventTracker development environment..."

# Handle reset flag
if [ "$RESET_DB" = true ]; then
  print_info "Resetting database (--reset flag set)..."
  if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1; then
    docker compose down -v
    print_status "Database reset"
  fi
fi

# Start Docker container
print_info "Starting PostgreSQL container..."
if docker container inspect "$CONTAINER_NAME" > /dev/null 2>&1 && docker ps --filter "name=$CONTAINER_NAME" | grep -q "$CONTAINER_NAME"; then
  print_status "PostgreSQL already running on port $DB_PORT"
else
  docker compose up -d
  print_status "PostgreSQL started"
fi

# Wait for PostgreSQL to be ready
print_info "Waiting for PostgreSQL to be ready..."
max_attempts=30
attempt=0

while [ $attempt -lt $max_attempts ]; do
  if docker exec "$CONTAINER_NAME" pg_isready -U "$DB_USER" > /dev/null 2>&1; then
    print_status "PostgreSQL is ready"
    break
  fi
  attempt=$((attempt + 1))
  sleep 1
done

if [ $attempt -eq $max_attempts ]; then
  print_error "PostgreSQL failed to start within ${max_attempts}s"
  print_info "Check logs with: docker logs $CONTAINER_NAME"
  exit 1
fi

# Create .env file
print_info "Creating .env file..."
cat > .env << EOF
# EventTracker Database Configuration
# Generated by dev-up.sh - do not commit to git

# Database Connection
DB_HOST=localhost
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USERNAME=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Full JDBC URL (used by Spring Boot)
JDBC_DATABASE_URL=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME

# Spring Boot Specific
spring.datasource.url=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME
spring.datasource.username=$DB_USER
spring.datasource.password=$DB_PASSWORD

# Alternative: Environment variable names expected by application.yml
eventstracker_JDBC_DATABASE_URL=jdbc:postgresql://localhost:$DB_PORT/$DB_NAME
eventstracker_JDBC_DATABASE_USERNAME=$DB_USER
eventstracker_JDBC_DATABASE_PASSWORD=$DB_PASSWORD

# RabbitMQ (local defaults, adjust if needed)
RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USERNAME=guest
RABBITMQ_PASSWORD=guest

# Application Server
SERVER_PORT=$APP_PORT
EOF

print_status ".env file created"

# Verify database exists
print_info "Verifying database..."
if docker exec -i "$CONTAINER_NAME" psql -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;" > /dev/null 2>&1; then
  print_status "Database verified"
else
  print_error "Failed to verify database"
  exit 1
fi

# Print next steps
echo ""
echo "════════════════════════════════════════════════════════════════"
echo -e "${GREEN}✓ EventTracker is ready!${NC}"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Database Details:"
echo "  Host:     localhost"
echo "  Port:     $DB_PORT"
echo "  Database: $DB_NAME"
echo "  User:     $DB_USER"
echo "  Password: $DB_PASSWORD"
echo ""
echo "Next Steps:"
echo "  1. Run the application:"
echo "     mvn spring-boot:run"
echo ""
echo "  2. Flyway migrations will run automatically on startup"
echo ""
echo "  3. View pgAdmin (optional):"
echo "     docker compose --profile pgadmin up -d"
echo "     Then: http://localhost:5050 (admin/admin)"
echo ""
echo "Useful Commands:"
echo "  Stop database:    docker compose down"
echo "  View logs:        docker logs $CONTAINER_NAME"
echo "  Connect via psql: psql -h localhost -U $DB_USER -d $DB_NAME"
echo "  Reset database:   ./dev-up.sh --reset"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
